### ISSUE TITLE
My Issue

### ISSUE THREAD

**Issue by AnxietyWump** [LyfeOnEdge/SSNCDISCORD#1] opened 2019-08-14 20:42 UTC
Your using Pyshit. use a real mans language like C#. :smug:

**Comment by LyfeOnEdge** [comment] 2019-08-19 06:36
@jkitl 
Closing issue.
Notes:
jkitl is an incel.
Conclusion:
jkitl could not reproduce.

**Closed as completed by LyfeOnEdge** 2019-08-19 06:37 UTC
